#ifndef SAPITRELLO_CSOPORT_11_DEFINES_H
#define SAPITRELLO_CSOPORT_11_DEFINES_H

#define INPUT_BUFFER_SIZE 1024
#define PARAM_BUFFER_SIZE 256
#define MAX_BOARD_NAME_LENGTH 30
#define MAX_CARD_TITLE_LENGTH 40
#define MAX_CARD_DESCRIPTION_LENGTH 200
#define MAX_USER_NAME_LENGTH 30
#define MAX_USER_EMAIL_LENGTH 50
#define CARD_BORDER_LENGTH 20

#endif //SAPITRELLO_CSOPORT_11_DEFINES_H